storage:
  cassandra:
    max_batch_size_rows: 50
    max_parallel_batches: 1000
    max_updates_job: 10
    connection:
      contactPoints: ["cassandra"]
      port: 9042
      consistency: LOCAL_QUORUM
      timeout: 10s
    store_name: peloton_test
    migrations: pkg/storage/cassandra/migrations/
  use_cassandra: true

master:
  port: 5289
  offer_hold_time_sec: 300
  offer_pruning_period_sec: 900
  db_write_concurrency: 40
  taskupdate_ack_concurrency: 10
  taskupdate_buffer_size: 10000

mesos:
  encoding: "x-protobuf"
  framework:
    user: "root"
    name: "Peloton"
    # TODO : add roles for other components
    role: "peloton-master"
    principal: "peloton"
    # ~100 weeks to failover
    failover_timeout: 60000000

election:
  zk_servers: ["zookeeper:2181"]
  root: "/peloton/development"

placement:
  task_dequeue_limit: 20
  offer_dequeue_limit: 10

job_manager:
