debug: true

aurorabridge:
  http_port: 5396

election:
  root: "/peloton"

health:
  heartbeat_interval: 5s

service_handler:
  # Include current and 5 previous runs task
  pod_runs_depth: 6
  thermos_executor:
    path: "/usr/share/aurora/bin/thermos_executor.pex"
    flags: "--preserve_env --nosetuid-health-checks --nosetuid --no-create-user"

event_publisher:
  # This is invalid value and must be set in production.yaml file
  kafka_url: localhost:1111
  publish_events: false
  # 16mb - increase size to workaround update instance event blowing up
  grpc_msg_size: 16777216

rate_limit:
  enabled: false
