logging:
  level: info

mesos:
  host_port: "localhost:5050"
  zk_path: "zk://localhost:8192/mesos"
  framework:
    revocable_resources: true

election:
  zk_servers: ["localhost:8192"]

metrics:
  multi_reporter: true
  prometheus:
    enable: true
  #statsd:
  #  enable: true
  #  endpoint: localhost:1234

k8s:
  enabled: false
  kubeconfig: /.kube/kind-config-peloton-k8s

storage:
  db_write_concurrency: 40

host_manager:
  host_pruning_period_sec: 30s
  host_placing_offer_status_sec: 30s
  #ToDo: move to lower case (match mesos resource type string)
  scarce_resource_types:
    - GPU
  host_drainer_period: 30s
  slack_resource_types:
    - cpus
