storage:
  cassandra:
    max_batch_size_rows: 50
    max_parallel_batches: 1000
    max_updates_job: 10
    connection:
      contactPoints: ["127.0.0.1"]
      port: 9042
      consistency: LOCAL_QUORUM
      timeout: 10s
    store_name: peloton_test
    migrations: pkg/storage/cassandra/migrations/
  use_cassandra: false

resmgr:
  http_port: 5290
  grpc_port: 5394
