logging:
  level: info

storage:
  db_write_concurrency: 40

election:
  zk_servers: ["localhost:8192"]

metrics:
  multi_reporter: true
  prometheus:
    enable: true
  #statsd:
  #  enable: true
  #  endpoint: localhost:1234

resmgr:
  entitlement_calculation_period: 5s
  preemption:
    enabled: true
    sustained_over_allocation_count: 3
    task_preemption_period: 10s
  host_drainer_period: 10s
  task:
    placing_timeout: 20s
    launching_timeout: 30s
    preempting_timeout: 20s
    reserving_timeout: 10m
    placement_retry_backoff: 10s
    placement_retry_cycle: 1
    enable_host_reservation: false
